spring:
  application:
    name: kurakani-monolith

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/chat-app-db
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  flyway:
    enabled: true
    baseline-on-migrate: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:aojha6822@gmail.com}
    password: ${MAIL_PASSWORD:randomasspassword}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


logging:
  level:
    root: off
#    org.springframework.security: DEBUG
#    root: info

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /docs
    display-request-duration: true

storage:
  endpoint: ${STORAGE_ENDPOINT:http://127.0.0.1:9000}
  access-key: ${STORAGE_ACCESS_KEY:rustfsadmin}
  secret-key: ${STORAGE_SECRET_KEY:rustfsadmin}
  bucket: ${STORAGE_BUCKET:kurakaani}
  region: ${STORAGE_REGION:rustfs}

app:
  jwt:
    secret: ${JWT_SECRET:TOYLwSbD3s8U0SmuFuVSBWJDa0dlyoXbjSDmDgEXnEN}
    expiration-seconds: ${JWT_EXPIRATION_SECONDS:864000}

