CREATE TABLE messages
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sender_id  BIGINT                                  NOT NULL,
    room_id    BIGINT,
    content    VARCHAR(255),
    is_edited  BOOLEAN DEFAULT FALSE,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_messages PRIMARY KEY (id)
);

CREATE TABLE password_reset_token
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token      INTEGER                                 NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE,
    used       BOOLEAN,
    CONSTRAINT pk_password_reset_token PRIMARY KEY (id)
);

CREATE TABLE roles
(
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (role_id)
);

CREATE TABLE room_members
(
    room_member_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    room_id        BIGINT                                  NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    room_role      VARCHAR(255),
    joined_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_room_members PRIMARY KEY (room_member_id)
);

CREATE TABLE rooms
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    type        VARCHAR(255),
    created_by  BIGINT                                  NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_rooms PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name         VARCHAR(255)                            NOT NULL,
    password          VARCHAR(255)                            NOT NULL,
    email             VARCHAR(255),
    enabled           BOOLEAN                                 NOT NULL,
    profile_image_url VARCHAR(255),
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE users_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_users_roles PRIMARY KEY (role_id, user_id)
);

ALTER TABLE rooms
    ADD CONSTRAINT uc_6fe13bb4f86f3f7af2c527046 UNIQUE (name);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_name UNIQUE (name);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_user_name UNIQUE (user_name);

ALTER TABLE rooms
    ADD CONSTRAINT uk_createdBy_roomName UNIQUE (created_by, name);

ALTER TABLE room_members
    ADD CONSTRAINT uk_user_room UNIQUE (room_id, user_id);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_ROOM FOREIGN KEY (room_id) REFERENCES rooms (id);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_SENDER FOREIGN KEY (sender_id) REFERENCES users (id);

ALTER TABLE password_reset_token
    ADD CONSTRAINT FK_PASSWORD_RESET_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE rooms
    ADD CONSTRAINT FK_ROOMS_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES users (id);

ALTER TABLE room_members
    ADD CONSTRAINT FK_ROOM_MEMBERS_ON_ROOM FOREIGN KEY (room_id) REFERENCES rooms (id);

ALTER TABLE room_members
    ADD CONSTRAINT FK_ROOM_MEMBERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES roles (role_id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (id);