CREATE TABLE messages
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sender_id  BIGINT                                  NOT NULL,
    room_id    BIGINT,
    content    VARCHAR(255),
    is_edited  BOOLEAN,
    is_deleted BOOLEAN,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_messages PRIMARY KEY (id)
);

CREATE TABLE room_members
(
    room_member_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    room_id        BIGINT                                  NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    room_role      VARCHAR(255),
    joined_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_room_members PRIMARY KEY (room_member_id)
);

CREATE TABLE rooms
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    type        VARCHAR(255),
    created_by  BIGINT                                  NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_rooms PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    user_id BIGINT       NOT NULL,
    role    VARCHAR(255) NOT NULL
);

CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email        VARCHAR(255)                            NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    last_seen_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_ROOM FOREIGN KEY (room_id) REFERENCES rooms (id);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_SENDER FOREIGN KEY (sender_id) REFERENCES users (id);

ALTER TABLE rooms
    ADD CONSTRAINT FK_ROOMS_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES users (id);

ALTER TABLE room_members
    ADD CONSTRAINT FK_ROOM_MEMBERS_ON_ROOM FOREIGN KEY (room_id) REFERENCES rooms (id);

ALTER TABLE room_members
    ADD CONSTRAINT FK_ROOM_MEMBERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_on_app_user FOREIGN KEY (user_id) REFERENCES users (id);