CREATE TABLE friendships
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    requester_id BIGINT                                  NOT NULL,
    recipient_id BIGINT                                  NOT NULL,
    status       VARCHAR(255),
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_friendships PRIMARY KEY (id)
);

ALTER TABLE friendships
    ADD CONSTRAINT uk_friendship UNIQUE (requester_id, recipient_id);

ALTER TABLE friendships
    ADD CONSTRAINT FK_FRIENDSHIPS_ON_RECIPIENT FOREIGN KEY (recipient_id) REFERENCES users (id);

ALTER TABLE friendships
    ADD CONSTRAINT FK_FRIENDSHIPS_ON_REQUESTER FOREIGN KEY (requester_id) REFERENCES users (id);