CREATE TABLE password_reset_token
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token      INTEGER                                 NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE,
    used       BOOLEAN,
    CONSTRAINT pk_password_reset_token PRIMARY KEY (id)
);

ALTER TABLE password_reset_token
    ADD CONSTRAINT FK_PASSWORD_RESET_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);